### ISSUE TITLE
Two column layout page margins

### ISSUE THREAD

**Issue by lspitzner** [haskell/hackage-server#722]
I noticed that with the two-column layout, the width of the middle part changes when the window width changes, even though there still is space left in the margins. I consider this a "design bug". To clarify, with some imaginary pixel values:

Should be:
- window 1000px: 200px 600px 200px
- window 800px: 100px 600px 100px

Currently:
- window 1000px: 200px 600px 200px
- window 800px: 150px 500px 150px

**Comment by gbaz** [comment]
No, this is by design. We use viewport relative sizing.

**Comment by lspitzner** [comment]
Wait, I don't mean the use of media-queries to adapt for smaller devices. I mean the changes happening inside the same "device category", layout-wise.

If that was not the misunderstanding, I'll clearly state my strong -1 on this, and point out that github, the documentation of racket, scala, elixir, rust all do not do this (but they of course use media-queries, too).

**Comment by gbaz** [comment]
No it isn't a misunderstanding. The margins and content don't just "jump" at the boundaries. They resize relative to the window within each range. So indeed the center content isn't at a fixed-width-per-viewport range, but a dynamic one.

I don't see what's wrong with this? It means that more efficient use of space can be made on wider browser windows.

**Comment by lspitzner** [comment]
> It means that more efficient use of space can be made on wider browser windows.

I don't understand "more efficient use of space". The most efficient use of space is to not to have margins. The reason to have margins is to restrict the number of words per line to some upper bound that keeps things readable. This upper bound does not scale with window/viewport width. I must be missing some aspect to this.

> the last design also had text that flowed to the width of the page, rather than being in a fixed-width div

I cannot reproduce this, at least when considering the package overview page. For example, things are still "fine" [here on 18/03/17](http://web.archive.org/web/20180317010811/https://hackage.haskell.org/package/lens).

**Comment by gbaz** [comment]
Ah, I see. We always had a max-width of 60em. Currently we have no max-width. I think I missed this because I tend to keep my browser windows narrower, and also because I checked the haddocks and they don't have a max-width. Fair point!

@NunoAlexandre what do you think about a max-width to the content?

**Comment by gbaz** [comment]
I think this should be addressed by the large-screens media query in https://github.com/haskell/hackage-server/pull/731

**Comment by gbaz** [comment]
(it does not fix the width of the content to a single number, but it _does_ mean that at large sizes there are much larger margins).

**Comment by NunoAlexandre** [comment]
> @NunoAlexandre what do you think about a max-width to the content?

The #content already has a max-width of 1450px;

I don't quite understand the overall issue here, I think.
Currently, this 2-col layout is available for viewports larger than 1280px, in which the #content takes `60vw`, i.e, 768px. An issue present currently, and [fixed in this PR](#731), is that the properties column and table grow different (the table outgrows the column itself) and another issue is that the column claims a min-width: 350px and asks for width: 25vw; Both of the issues leads to bugs like overlap on zooming and the issue - I think - reported here.

On my PR I changed the way this column claims space so that it only asks `width: 30%;`, meaning it will never outgrow the #container itself on zoom. Also, I make sure the table itself does not outgrow the column. Anyway, 30% of 60vw is, at least, 230px, which is already enough, considering I change the style of this table so that the label of each value is placed on top of it instead of next to it, each was wasting us a lot of space.

**Comment by gbaz** [comment]
@lspitzner do you think the changes as suggested by Nuno resolve this for you?

**Comment by lspitzner** [comment]
@gbaz Uhm, no. The preview still shows the behaviour described in my first comment, and as a consequence, characters/words per line changes depending on viewport size (and also when zooming).

@NunoAlexandre if you don't understand my reasoning above, then let me instead ask you: Why do we waste space at all by having any margins?

I gave my answer to this above:

> I don't understand "more efficient use of space". The most efficient use of space is not to have margins. The reason to have margins is to restrict the number of words per line to some upper bound that keeps things readable. This upper bound does not scale with window/viewport width.

And as a consequence of this reasoning, you simply would not give a (max-)width in terms of `vw`, but in terms of `em` or `px`. This also ensures that zooming does not change the characters/words per line as it does now.

This is what other docs do. This is what github does, just try zooming in this page. You get a bit of jitter, but words per line essentially remains constant. This is what reddit does (comments have some upper width limit). Or google (the trivial search result page). Or stackoverflow.

I am curious what the reasoning is behind deviating from this de-facto default.

Further I don't understand why the "Readme" section gets more space than the left column above. If the package description has optimal readability at 90-100 characters per line, why do we pester the reader with ~160 characters per line in the readme? (I am basing this on the live page and not the preview, as `monoid-extra` has no readme.) It seems to me that other relevant metrics (font size, line margin, character spacing) are the same.

[rust's crates.io](https://crates.io/crates/serde) and [npm's package view](https://www.npmjs.com/package/chat?activeTab=readme) use a rather similar two-column setup (was that the inspiration?) and they simply keep the left column all the way down, or at least until the end of text.

**Comment by gbaz** [comment]
@lspitzner ok, so I want to understand you. We have content-width max widths on the content at _each individual_ resolution-range. However, we resize dynamically _within_ that range (using plain old width, not max-width). What you are saying is you think we should _always_ be fixed in each range, and not even have constrained resizing with a sane max-width?

Is this because you think there is just some max-width beyond which we should not go? I.e. if we set the fixed max-width to something lower than 1450px would that suffice? Or do you oppose the idea of any sort of dynamic resizing at all, no matter the hard stop on max-width?

**Comment by gbaz** [comment]
by the way, with my browser window at max-width for my screen I see the following, comparing Nuno's current proposed pages to the web.archive.org ones:

![image](https://user-images.githubusercontent.com/1125849/37997430-d7dd7e18-31e8-11e8-9833-54c8c8500680.png)

![image](https://user-images.githubusercontent.com/1125849/37997446-e4b4a21a-31e8-11e8-9690-d410ad39117d.png)

So with the wider font, at least in the presence of the sidebar, we actually have fewer characters per line.

I agree that without the sidebar it gets a bit bigger:

![image](https://user-images.githubusercontent.com/1125849/37997624-74c94a22-31e9-11e8-9511-e47d2473f4a3.png)

![image](https://user-images.githubusercontent.com/1125849/37997634-807cf6ac-31e9-11e8-9776-dc3fb8edf367.png)

@NunoAlexandre what do you think about bumping the max-width down a bit further, to say 1100?

**Comment by lspitzner** [comment]
@gbaz what is the advantage of dynamic resizing?

**Comment by lspitzner** [comment]
And unless there is a good answer to that question, I indeed think that hackage should follow the rest of the web and use a simple `max-width` in `px` or `em`.

**Comment by gbaz** [comment]
@lspitzner there appears to be some confusion. We _do_ use a `max-width` in `px`. It just happens to be rather large (1450px to be precise). For windows where the table cannot flow to max width, it is instead resized to be a percentage of the total. This is _exactly_ as it was in hackage before, except before there was a significantly smaller `max-width` (around 960px).

**Comment by lspitzner** [comment]
> This is _exactly_ as it was in hackage before [..]

False. Before the re-design there was only `max-width` defined, no `width`.

**Comment by lspitzner** [comment]
If I am mistaken, please link the relevant web.archive.org site and the lines in the css where you see `width` being defined.

**Comment by gbaz** [comment]
You're correct on the specifics. There's only a padding and a max-width. However, the effect is what I described. If I made the window sufficiently smaller, the text reflowed. Contrast that to e.g. github where we now type, where if the window becomes smaller, the text does not reflow.

Either way, I just want to understand your specific objection. It seems to be that you do not want text to reflow when the window resizes, regardless of if there is a max-width that prevents the lines from becoming too long at large sizes. Is this correct?

**Comment by NunoAlexandre** [comment]
@gbaz I would be rather happy reducing the max-width, I never wanted it that big myself. This being said, such a max-width is friendly for larger screens such as 4k displays, which are becoming more popular amongst developers. I don't think, however, how that plays a role here.

@lspitzner thanks for your patience. Indeed when zooming on Reddit the whole page gets bigger and overflows the viewport - but that doesn't mean it's the right way. The [Times](https://www.thetimes.co.uk/edition/news/pay-more-at-the-till-for-drinks-cans-and-bottles-d9j7f25sf), [Apple](https://apple.com/mac), the [Rust docs](https://doc.rust-lang.org/book/second-edition/), the [MDN web docs](https://developer.mozilla.org/en-US/docs/Web/CSS/text-size-adjust), [Google's Adwords docs](https://developers.google.com/adwords/api/docs/reference/v201710/AdGroupAdService), [Youtube](https://www.youtube.com/watch?v=9NLZCLKppZs) and many, many more do zoom like we do here. 

Perhaps it would be better if you explain your intention and how we could improve your experience while keeping a good zoom behavior.

**Comment by lspitzner** [comment]
@NunoAlexandre 

> The Times, Apple, the Rust docs, the MDN web docs, Google's Adwords docs, Youtube and many, many more do zoom like we do here.

I cannot reproduce this. In the rust docs, when there are margins, average characters per line is a constant over zooming. On current hackage and in the preview, this is not the case.

> Perhaps it would be better if you explain your intention.

Perhaps it would be better if you re-read my previous explanations. Perhaps it would be better if you explained why you changed the way margins and zooming worked, or if @gbaz explained what the advantages of "dynamic resizing" are supposed to be.

Oh, also @gbaz I do not understand your last comment, at all. Why bring up github and its behaviour in the case _where there are no margins_ in a discussion about _margins on hackage_?

I am not happy about the way this discussion goes, and how you two repeatedly make factually false statements that are imprecise or careless at best, and expect me to provide even more explanation in the presence of such lack of attention from your part.

**Comment by gbaz** [comment]
@lspitzner Sorry for the poor communication. I have been trying very hard to understand what you are asking about. It is not malice or lack of attention. It is me genuinely trying and failing to understand. I know that using the term "dynamic resizing" may have caused more confusion than not. All I meant to say is that things resize relative to the page -- which personally I have always thought was just how most things on the web always used to work?

Up until just now, I thought your issue was with _resizing_ the window, and the relative width of the text area within it. Now, I see that your issue is best expressed as what happens when one _zooms_ the window, via command-plus or the like. So the use-case is essentially that when you want to zoom in, or out, you would like it that the text not rewrap? (Or rewrap very little?) Is that a more precise statement of what you would like to resolve?

**Comment by NunoAlexandre** [comment]
> @lspitzner Sorry for the poor communication. I have been trying very hard to understand what you are asking about. It is not malice or lack of attention. It is me genuinely trying and failing to understand. 

I make these words mine as well. @lspitzner perhaps you are right that there is lack of attention on my part, and I am sorry for that, but it seems that both I and @gbaz don't find it easy to understand you and I do not have the time to re-read your comment 10 times and hope for the best.

**Comment by lspitzner** [comment]
I am sorry, but I think I have explained my position as well as I am able to. Indeed, the "dynamic resizing" phrase is not defined and me using it might have led to confusion. I shall be more careful in the future.

To keep things constructive, two things. Firstly you proposed to reduce the `max-width` on the current design. I welcome this change; it is definitely a step in the right direction from my perspective. Secondly, if I find the time, I might make a PR in the future (perhaps when the other changes have settled down) to implement things how I'd like to see them. Having a clear "counterproposal" should be much more useful than continuing this discussion on the dry.

Thank you very much for your time and attention, and again for pushing for improving the user experience for all hackage users.

**Comment by gbaz** [comment]
> There were no proper margins before, the content took the whole screen.

@NunoAlexandre this is what I thought too. But it turns out this was because I never resized my window large enough! At a large enough size, you can see that there was a fixed max-width at `60em`:  http://web.archive.org/web/20170724043003/http://hackage.haskell.org/

You will also see that as you zoom in and out, or resize once the table is at full width, the text does not rewrap. (However, if you make the window sufficiently small, then it of course does reflow rather than force horizontal scroll).

@lspitzner again, sorry for not having been able to better follow/steer the discussion. I think this really may be the case where a few lines of css speak a thousand words, and such a counterproposal could help focus things when you find the time.

**Comment by NunoAlexandre** [comment]
> @NunoAlexandre this is what I thought too. But it turns out this was because I never resized my window large enough! At a large enough size, you can see that there was a fixed max-width at 60em: http://web.archive.org/web/20170724043003/http://hackage.haskell.org/

@gbaz I meant really margins, not absolute upper bound. 

@lspitzner thanks, really and I am sorry for the frustration.
